TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += separator.db
DB += separator_power_status.db
DB += separator_voltage.db
DB += separator_current.db

#protocol files
DATA += separator.proto

#=======================================
include $(TOP)/configure/RULES
