TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += separator.db

#protocol files
DATA += separator.proto

#=======================================
include $(TOP)/configure/RULES
